### ISSUE TITLE
Create sample application 

### ISSUE THREAD

**Issue by danilodcn** [bhomnick/django-nonrelated-inlines#4]
for a better understanding of how to use the application it would be good to create some examples of use

**Comment by bhomnick** [comment]
@danilodcn Thanks for your comment.  If you look in the tests folder you'll see a sample app: https://github.com/bhomnick/django-nonrelated-inlines/tree/master/nonrelated_inlines/tests

**Comment by etanter** [comment]
FWIW I can report that following the README.md I was able to integrate this in my app, and it works like a charm so far!
Thanks a lot @bhomnick 🙏🏻

**Comment by bhomnick** [comment]
Great, thanks!

**Comment by etanter** [comment]
Actually, there's one issue in the interaction with [django-baton](https://github.com/otto-torino/django-baton): nonrelated inlines are not handled as normal inlines by Baton when it comes to configuring tabs. I have no idea why.

Not sure if I should report it here or there. Any opinion/preference? (ping @abidibo)

**Comment by bhomnick** [comment]
Can you please create a new issue?  It would also be great if you can provide an example app demonstrating the issue.
