### ISSUE TITLE
ordering not considered

### ISSUE THREAD

**Issue by etanter** [bhomnick/django-nonrelated-inlines#6]
Hi, 
I'm trying to use the `ordering` field in a nonrelated inline, but it is not taken into account.
I have project objects, with a `year` attribute, and despite putting `ordering = ['year']`, the inlines show up in an order that reflects their ids instead of their year attribute.
Any idea?
Thanks!

**Comment by bhomnick** [comment]
@etanter Have you tried adding an `order_by()` to the `get_form_queryset()` method?

**Comment by etanter** [comment]
D'oh! Thanks!
